[package]
name = "vanity-rage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rayon" = "1.8.0"
"age" = "0.9.2"
"glob-match" = "0.2.1"
"chrono" = "0.4.31"
